version: '3.8'

services:
  backend:
    image: ghcr.io/subhan-khaliq/trinity-backend:latest
    env_file:
      - .env.production
    ports:
      - "5001:5001" # Match container port with host
    restart: always

  frontend:
    image: ghcr.io/subhan-khaliq/trinity-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
